name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        required: true
        description: "Version bump type"
        options:
        - patch
        - minor
        - major
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: |
          pip install --upgrade pip
          pip install poetry==1.8.4

      - name: Update PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Bump Version
        run: |
          poetry version "${{ github.event.inputs.version }}"
          CURRENT_VERSION=$(poetry version --short)
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV

      - name: Fail if the current version doesn't exist
        if: env.CURRENT_VERSION == ''
        run: exit 1

      - name: Build project for distribution
        run: poetry build

      - name: Commit new version
        run: |
          git config --global user.name "GitHub Actions for Python project"
          git config --global user.email "<>"
          git commit -a -m "Bump version to $CURRENT_VERSION"
          git push origin main

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.whl"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          generateReleaseNotes: true
          tag: ${{ env.CURRENT_VERSION }}
          commit: main